version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "mongo",
    "jquery"
  ]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/ItheManil/Manilblk"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "php"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "shell"